export const CHANGE_BANNERS = "/home-music/CHANGE_BANNERS";
export const CHANGE_RECOMMENDSONGS = "/home-music/CHANGE_RECOMMENDSONGS";
export const CHANGE_NEWRANKINGS = "/home-music/CHANGE_NEWRANKINGS";
export const CHANGE_ORIGINRANKING = "/home-music/CHANGE_ORIGINRANKING";
export const CHANGE_UPDATERANKING = "/home-music/CHANGE_UPDATERANKING";
export const CHANGE_HOTSONGMENU = "/home-music/CHANGE_HOTSONGMENU";
export const CHANGE_RECOMMENDSONGMENU = "/home-music/CHANGE_RECOMMENDSONGMENU";
